---
#updated #now
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gatekeeper
  namespace: gatekeeper-system
spec:
  interval: 5m0s
  path: ./deploy
  prune: true
  #serviceAccountName: opa-gatekeeper-admin
  sourceRef:
    kind: GitRepository
    name: gatekeeper
