---
#Updates
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gatekeeper
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: test-1
  url: https://github.com/open-policy-agent/gatekeeper
