apiVersion: rbac.authorization.k8s.io/v1
#kind: Role
kind: ClusterRole
metadata:
  namespace: gatekeeper-system
  name: opa-gatekeeper-admin
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs:
      ["get", "assign", "list", "watch", "create", "update", "patch", "delete"]
