apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: gatekeeper-system
  name: opa-gatekeeper-admin-binding
roleRef:
  kind: ClusterRole
  name: opa-gatekeeper-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts
  - kind: ServiceAccount
    name: gatekeeper-system
    apiGroup: rbac.authorization.k8s.io
