---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: opa
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: test-2
  url: https://github.com/open-policy-agent/gatekeeper
